AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys Jenkins to an existing kubernetes cluster"

Parameters:
  EksClusterName:
    Type: String
  Namespace:
    Type: String
    Default: jenkins
    Description: (Optional) Kubernetes namespace to deploy Jenkins into.
Resources:

  JenkinsNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: !Ref Namespace
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${Namespace}

  JenkinsServiceAccount:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: JenkinsNamespace
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: !Ref Namespace
      Manifest: !Sub |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          labels:
            app.kubernetes.io/name: jenkins
          name: jenkins

  JenkinsHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: JenkinsServiceAccount
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: !Ref Namespace
      Repository: https://charts.jenkins.io
      Chart: stable/jenkins
      ValueYaml: |
        controller:
          # Used for label app.kubernetes.io/component
          componentName: "jenkins-controller"
          image: "jenkins/jenkins"
          tag: "2.289.2-lts-jdk11"
          additionalPlugins:
            - aws-codecommit-jobs:0.3.0
            - aws-java-sdk:1.11.995
            - junit:1.51
            - ace-editor:1.1
            - workflow-support:3.8
            - pipeline-model-api:1.8.5
            - pipeline-model-definition:1.8.5
            - pipeline-model-extensions:1.8.5
            - workflow-job:2.41
            - credentials-binding:1.26
            - aws-credentials:1.29
            - credentials:2.5
            - lockable-resources:2.11
            - branch-api:2.6.4
          resources:
            requests:
              cpu: "1024m"
              memory: "4Gi"
            limits:
              cpu: "4096m"
              memory: "8Gi"
          javaOpts: "-Xms4000m -Xmx4000m"
          servicePort: 80
          serviceType: LoadBalancer
        agent:
          Enabled: false
        rbac:
          create: true
        serviceAccount:
          create: false
          name: "jenkins"

Outputs:
  JenkinsHelmChart:
    Value: !Ref JenkinsHelmChart
