AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys Spinnaker to an existing kubernetes cluster"

Parameters:
  EksClusterName:
    Type: String
  SpinnakerVersion:
    Type: String
  OperatorNamespace:
    Type: String
    Default: spinnaker-operator
    Description: Kubernetes namespace to deploy Spinnaker operator.
  GitHubUser:
    Type: String
    Description: GitHub username or organization
    MinLength: 3
    MaxLength: 100
    ConstraintDescription: You must enter a GitHub username or organization
  GitHubTokenSecretsManager:
    NoEcho: true
    Type: String
    Default: '{{resolve:secretsmanager:/spinnaker/githubtoken:SecretString:GHToken}}'
    Description: GitHub Token. Must be defined in AWS Secrets Manager. https://github.com/settings/tokens
  ECRName:
    Type: String
    Default: 'spinnaker'
    Description: Name to be used for ECR repo.

#  CreateSpinnakerUser:
#    Type: String
#    Allowedvalues: ['Enabled','Disabled']
#    Default: 'Disabled'
#    Description: 'This is required to deploy Spinnaker but we default to disabled to force awareness of IAM user creation'

Resources:
  SpinnakerUser:
    Type: AWS::IAM::User
    Description: User identity Spinnaker uses to create AWS resources
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess

  SpinnakerAccessKey:
    DependsOn: SpinnakerUser
    Type: AWS::IAM::AccessKey
    Description: Generate AccessKey for Spinnaker
    Properties:
      UserName: !Ref SpinnakerUser

  SpinnakerAccessKeyCredentials:
    DependsOn: SpinnakerAccessKey
    Type: AWS::SecretsManager::Secret
    Description: Store the access key credentials for Spinnaker in a secure location
    Properties:
      Description: Spinnaker user access key credentials
      SecretString: !Sub |
        {
          "AccessKeyId":"${SpinnakerAccessKey}",
          "SecretAccessKey":"${SpinnakerAccessKey.SecretAccessKey}"
        }

  SpinnakerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRName
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: 'AES256'
      ImageTagMutability: 'IMMUTABLE'

  SpinnakerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'spinnaker-bucket${AWS::Region}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SpinnakerOperatorNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: 'kube-system'
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${OperatorNamespace}

  SpinnakerHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    #    DependsOn: SpinnakerServiceAccount
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: !Ref OperatorNamespace
      Repository: 'https://armory.jfrog.io/artifactory/charts/'
      Chart: 'armory/armory-spinnaker-operator'
      Values:
        spinnakerService.enabled: true

  TokenRefreshConfigmap:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: SpinnakerOperatorNamespace
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: spinnaker   #note that this namespace differs from the operator namespace. this is the service ns.
      Manifest: !Sub |
        apiVersion: v1
        data:
          config.yaml: |
            interval: 30m # defines refresh interval
            registries: # list of registries to refresh
              - registryId: "${AWS::AccountId}"
                region: "${AWS::Region}"
                passwordFile: "/etc/passwords/my-ecr-registry.pass"
        kind: ConfigMap
        metadata:
          name: token-refresh-config
          namespace: spinnaker


  SpinnakerServiceAccount:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: SpinnakerOperatorNamespace
    Properties:
      ClusterName: !Ref EksClusterName
      Namespace: !Ref OperatorNamespace
      Manifest: !Sub |
        apiVersion: spinnaker.io/v1alpha2
        kind: SpinnakerService
        metadata:
          name: spinnaker
          namespace: spinnaker
        spec:
          spinnakerConfig:
            config:
              version: ${SpinnakerVersion}   # the version of Spinnaker to be deployed
              persistentStorage:
                persistentStoreType: s3
                s3:
                  bucket: spinnaker-bucket${AWS::Region}-${AWS::AccountId}
                  rootFolder: front50
                  region: ${AWS::Region}
                  accessKeyId: ${SpinnakerAccessKey}
                  secretAccessKey: ${SpinnakerAccessKey.SecretAccessKey}
              deploymentEnvironment:
                sidecars:
                  spin-clouddriver:
                  - name: token-refresh
                    dockerImage: quay.io/skuid/ecr-token-refresh:latest
                    mountPath: /etc/passwords
                    configMapVolumeMounts:
                    - configMapName: token-refresh-config
                      mountPath: /opt/config/ecr-token-refresh
              features:
                artifacts: true
              artifacts:
                github:
                  enabled: true
                  accounts:
                  - name: ${GithubUser}
                    token: ${GitHubTokenSecretsManager} # GitHub's personal access token. This fields supports `encrypted` references to secrets.
              providers:
                  dockerRegistry:
                    enabled: true
                  kubernetes:
                    enabled: true
                    accounts:
                    - name: spinnaker-workshop
                      requiredGroupMembership: []
                      providerVersion: V2
                      permissions:
                      dockerRegistries:
                        - accountName: my-ecr-registry
                      configureImagePullSecrets: true
                      cacheThreads: 1
                      namespaces: [spinnaker,detail]
                      omitNamespaces: []
                      kinds: []
                      omitKinds: []
                      customResources: []
                      cachingPolicies: []
                      oAuthScopes: []
                      onlySpinnakerManaged: false
                      kubeconfigFile: kubeconfig-sp  # File name must match "files" key
                    primaryAccount: spinnaker-workshop  # Change to a desired account from the accounts array
            profiles:
                clouddriver:
                  dockerRegistry:
                    enabled: true
                    primaryAccount: my-ecr-registry
                    accounts:
                    - name: my-ecr-registry
                      address: ${SpinnakerRepository.RepositoryUri}
                      username: AWS
                      passwordFile: /etc/passwords/my-ecr-registry.pass
                      trackDigests: true
                      repositories:
                      - ${ECRName}
                igor:
                  docker-registry:
                    enabled: true
            files:
                kubeconfig-sp: |
                  <FILE CONTENTS HERE> # Content from kubeconfig created by Spinnaker Tool
          # spec.expose - This section defines how Spinnaker should be publicly exposed
          expose:
            type: service  # Kubernetes LoadBalancer type (service/ingress), note: only "service" is supported for now
            service:
              type: LoadBalancer


Outputs:
